name: oled_editor
description: A modern OLED HTML Editor.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Core Plugins
  webview_flutter: ^4.4.2
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  intl: ^0.19.0 # For date formatting in file list

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true