name: oled_editor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core Features
  webview_flutter: ^4.4.2
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  
  # UI & Editor
  google_fonts: ^6.1.0
  highlight: ^0.7.0
  code_text_field: ^2.3.0

# ðŸ›¡ï¸ THE FIX: FORCE COMPATIBILITY
dependency_overrides:
  intl: ^0.19.0
  web: ^0.5.0