name: oled_editor
description: A modern OLED HTML Editor.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core Plugins ---
  webview_flutter: ^4.4.2
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  
  # --- The Fix: Allow newer version ---
  intl: ^0.20.0  

  # --- Modern UI & Editor Tools ---
  google_fonts: ^6.1.0
  code_text_field: ^2.5.0
  highlight: ^0.7.0
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true